# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpicture', models.ImageField(upload_to='dp')),
                ('bio', models.CharField(max_length=50)),
                ('contacts', models.CharField(blank=True, max_length=12)),
                ('projectsposted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
    ]
