# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190320_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpicture',
            field=models.ImageField(default='download.jpeg', upload_to='dp'),
        ),
    ]
