# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190320_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpicture',
            field=models.ImageField(upload_to='dp'),
        ),
    ]
